analysis_type: "data_scaling"  # Change to 'data_scaling' as needed
device: "cuda"  # Change to 'cpu' if needed

analysis_kwargs:
  output_root: "./output/"  # Directory where the analysis folders will be created
  model_type: "nfst"  # Type of model to be used


  # Model-specific configurations (modify based on the model type)
  model_kwargs:
    dummy_input: null

  # Mock generation specific configurations
  mock_kwargs:
    field_size: 32
    total_num_triangles: 64
    ratio_left: 0.8  # Use list of many for sensitivity analysis
    length_side1: 4
    length_side2: 8

  # Training specific configurations
  training_kwargs:
    epochs: 50
    lr: 0.0001
    num_train_val_mocks: [50, 100, 200, 400, 800, 1600, 3200]  # Use list of many for data scaling analysis
    num_test_mocks: 3000


  # Additional parameters
  repeats: 5
  num_verification_catalogs: 1000
  premade_data: null
