analysis_type: "data_scaling"  # Change to 'data_scaling' as needed

analysis_kwargs:
  output_root: "./output/"  # Directory where the analysis folders will be created
  model_type: "nfst"  # Type of model to be used

  # Model-specific configurations (modify based on the model type)
  model_kwargs:
    size: 32
    num_scales: 3
    num_angles: 4
    subnet_hidden_sizes: [32, 32]
    reduction=: 'asymm_ang_avg'
    linear_hiddens: 128

  # Mock generation specific configurations
  mock_kwargs:
    field_size: 32
    total_num_triangles: 1000
    ratio_left: 0.7  # Use list of many for sensitivity analysis
    length_side1: 4
    length_side2: 8

  # Training specific configurations
  training_kwargs:
    epochs: 50
    learning_rate: 0.001
    num_train_val_mocks: [50, 100, 200, 400, 800, 1600]  # Use list of many for data scaling analysis
    num_test_mocks: 5000

  # Additional parameters
  repeats: 10
  num_verification_catalogs: 1000
  premade_data: null
